- import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'
- import_tasks: suse.yml
  when: ansible_os_family == 'Suse'

- name: auditbeat - get installed packages
  package_facts:

- name: auditbeat - install
  package:
      name: auditbeat
      state: present
- name: auditbeat - remove SysV startup when systemd is being used
  file:
      path: "/etc/init.d/auditbeat"
      state: absent
  when: "'systemd' in packages"
- name: auditbeat - remove default audit rules
  file:
      path: "/etc/auditbeat/audit.rules.d/{{ item }}"
      state: absent
  with_items:
      - sample-rules-linux-32bit.conf
      - sample-rules-linux-64bit.conf

- name: auditbeat - disable auditd
  service:
      name: auditd
      enabled: no
      state: stopped
  ignore_errors: true
- name: auditbeat - kill all auditd processes
  shell: "killall auditd || :"
- name: auditbeat - enable
  service:
      name: auditbeat
      enabled: yes
      state: started

- name: auditbeat - copy general configuration
  copy:
      src: ../files/auditbeat.general.yml
      dest: /etc/auditbeat/auditbeat.yml.d/
      owner: root
      group: root
      mode: 0600
- name: auditbeat - copy file output configuration
  copy:
      src: ../files/auditbeat.output-file.yml
      dest: /etc/auditbeat/auditbeat.yml.d/
      owner: root
      group: root
      mode: 0600
- name: auditbeat - assemble auditbeat.yml
  assemble:
      src: /etc/auditbeat/auditbeat.yml.d/
      dest: /etc/auditbeat/auditbeat.yml
      owner: root
      group: root
      mode: 0600
  notify: restart auditbeat

- name: auditbeat - get system users
  getent:
      database: passwd
- name: auditbeat - read the UID_MIN
  command:
  args:
      argv: [ 'sed', '-rne', 's/^UID_MIN[[:space:]]+([[:digit:]]+).*$/\1/ p', '/etc/login.defs' ]
      warn: false
  register: uidmin_cmd
  check_mode: no
  changed_when: false
- name: auditbeat - set the uid_min
  set_fact:
      uid_min: "{{ uidmin_cmd.stdout|default(500, true) }}"

- name: auditbeat - test for privilege escalation syscalls
  audit_syscall_facts:
      syscalls:
          - capset
          - setgroups
          - setgroups32
- name: auditbeat - set privilege escalation syscalls facts
  set_fact:
      privesc_syscalls_b32: "{{ syscalls_b32|sort }}"
      privesc_syscalls_b64: "{{ syscalls_b64|sort }}"

- name: auditbeat - test for privileged set user/group syscalls
  audit_syscall_facts:
      syscalls:
          - setgid
          - setgid32
          - setregid
          - setregid32
          - setresgid
          - setresgid32
          - setfsgid
          - setfsgid32
          - setuid
          - setuid32
          - setreuid
          - setreuid32
          - setresuid
          - setresuid32
          - setfsuid
          - setfsuid32
- name: auditbeat - set privileged set user/group syscalls facts
  set_fact:
      ugidset_syscalls_b32: "{{ syscalls_b32|sort }}"
      ugidset_syscalls_b64: "{{ syscalls_b64|sort }}"

- name: auditbeat - test for other syscalls
  audit_syscall_facts:
      syscalls:
          - bpf
          - prctl
          - prlimit64
- name: auditbeat - set other syscalls facts
  set_fact:
      other_syscalls_b32: "{{ syscalls_b32|sort }}"
      other_syscalls_b64: "{{ syscalls_b64|sort }}"

- name: auditbeat - test for simple privileged syscalls
  audit_syscall_facts:
      syscalls:
          - mlock
          - mlock2
          - mlockall
          - munlock
          - munlockall
          - mount
          - umount
          - umount2
          - swapon
          - swapoff
          - setrlimit
          - create_module
          - delete_module
          - init_module
          - finit_module
          - kexec_file_load
          - kexec_load
- name: auditbeat - set simple syscalls facts
  set_fact:
      simple_syscalls_b32: "{{ syscalls_b32|sort }}"
      simple_syscalls_b64: "{{ syscalls_b64|sort }}"

- name: auditbeat - test for privileged time syscalls
  audit_syscall_facts:
      syscalls:
          - adjtimex
          - settimeofday
          - clock_adjtime
          - clock_settime
          - stime
- name: auditbeat - set time syscalls facts
  set_fact:
      time_syscalls_b32: "{{ syscalls_b32|sort }}"
      time_syscalls_b64: "{{ syscalls_b64|sort }}"

- name: auditbeat - test for mmap syscalls
  audit_syscall_facts:
      syscalls: [ mmap, mmap2 ]
- name: auditbeat - set mmap syscalls facts
  set_fact:
      mmap_syscalls_b32: "{{ syscalls_b32|sort }}"
      mmap_syscalls_b64: "{{ syscalls_b64|sort }}"

- name: auditbeat - find auditd binaries
  find:
      paths: [ /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /snap/bin, /usr/local/libexec, /usr/libexec, /libexec ]
      recurse: no
      follow: no
      file_type: any
      patterns: [ auditctl, auditd ]
  register: auditd_bins
- name: auditbeat - find auditbeat binaries
  find:
      paths: [ /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /snap/bin, /usr/local/libexec, /usr/libexec, /libexec ]
      recurse: no
      follow: no
      file_type: any
      patterns: [ auditbeat ]
  register: auditbeat_bins
- name: auditbeat - find passwd binaries
  find:
      paths: [ /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /snap/bin, /usr/local/libexec, /usr/libexec, /libexec ]
      recurse: no
      follow: no
      file_type: any
      patterns: [ passwd ]
  register: passwd_bins
- name: auditbeat - find user and group mod binaries
  find:
      paths: [ /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /snap/bin, /usr/local/libexec, /usr/libexec, /libexec ]
      recurse: no
      follow: no
      file_type: any
      patterns: [ groupadd, groupmod, addgroup, useradd, usermod, adduser, sss_groupadd, sss_groupdel, sss_groupmod, sss_useradd, sss_userdel, sss_usermod ]
  register: usergroup_bins
- name: auditbeat - find startup script directories
  find:
      paths: [ /etc ]
      recurse: no
      follow: no
      file_type: directory
      patterns: [ init.d, init, rc.d, rc0.d, rc1.d, rc2.d, rc3.d, rc4.d, rc5.d, rc6.d, rcS.d ]
  register: startupscript_dirs
- name: auditbeat - find systemd binaries
  find:
      paths: [ /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /snap/bin, /usr/local/libexec, /usr/libexec, /libexec ]
      recurse: no
      follow: no
      file_type: any
      patterns: [ systemctl ]
  register: systemd_bins
  when: "'systemd' in packages"
- name: auditbeat - find su and sudo binaries
  find:
      paths: [ /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /snap/bin, /usr/local/libexec, /usr/libexec, /libexec ]
      recurse: no
      follow: no
      file_type: any
      patterns: [ su, sudo ]
  register: susudo_bins
- name: auditbeat - find power state binaries
  find:
      paths: [ /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /snap/bin, /usr/local/libexec, /usr/libexec, /libexec ]
      recurse: no
      follow: no
      file_type: any
      patterns: [ shutdown, poweroff, reboot, halt ]
  register: powerstate_bins
- name: auditbeat - find network binaries
  find:
      paths: [ /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /snap/bin, /usr/local/libexec, /usr/libexec, /libexec ]
      recurse: no
      follow: no
      file_type: any
      patterns: [ iptables, iptables-restore, iptables-save, iptables-apply, xtables-multi, ifconfig, route, ip, nmcli, netplan, netplan-generate, netplan-apply, netplan-try, wicked, ethtool ]
  register: network_bins
- name: auditbeat - find network configurations
  find:
      paths: [ /etc, /etc/sysconfig, /etc/default ]
      recurse: no
      follow: no
      file_type: any
      patterns: [ network, network-scripts, networking, netplan, networkd-dispatcher, NetworkManager, wicked ]
  register: network_confs
- name: auditbeat - find firewalld binaries
  find:
      paths: [ /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /snap/bin, /usr/local/libexec, /usr/libexec, /libexec ]
      recurse: no
      follow: no
      file_type: any
      patterns: [ firewall-cmd, firewall-offline-cmd, firewalld ]
  register: firewalld_bins
  when: "'firewalld' in packages"
- name: auditbeat - find firewalld configurations
  find:
      paths: [ /etc, /etc/sysconfig, /etc/default, /usr/lib ]
      recurse: no
      follow: no
      file_type: any
      patterns: [ firewalld ]
  register: firewalld_confs
  when: "'firewalld' in packages"
- name: auditbeat - find crontab spool
  find:
      paths: [ /var/spool/cron ]
      recurse: no
      follow: no
      file_type: directory
      patterns: [ crontabs, tabs ]
  register: crontab_spool
- name: auditbeat - find atjob spool
  find:
      paths: [ /var/spool, /var/spool/cron ]
      recurse: no
      follow: no
      file_type: directory
      patterns: [ atjobs, at ]
  register: atjob_spool

- name: auditbeat - generate IT04.6.1 audit rules
  template:
      src: ../templates/audit-rules.00_it0461.conf.j2
      dest: /etc/auditbeat/audit.rules.d/00_it0461.conf
      owner: root
      group: root
      mode: 0644
  notify: restart auditbeat
- name: auditbeat - generate IT04.6.1 audit syscall rules
  template:
      src: ../templates/audit-rules.99_it0461.conf.j2
      dest: /etc/auditbeat/audit.rules.d/99_it0461.conf
      owner: root
      group: root
      mode: 0644
  notify: restart auditbeat
