- name: auditbeat - import elastic.co rpm gpg key
  rpm_key:
      key: https://packages.elastic.co/GPG-KEY-elasticsearch
      state: present
- name: auditbeat - add elastic.co rpm repository
  zypper_repository:
      name: elastic-6.x
      description: Elastic repository for 6.x packages
      repo: https://artifacts.elastic.co/packages/6.x/yum
      auto_import_keys: yes
      disable_gpg_check: no
      enabled: yes

- name: auditbeat - install audit
  package:
      name: audit
      state: present
